### ISSUE TITLE
Download BDD-A

### ISSUE THREAD

**Issue by shuyulou** [ykotseruba/SCOUT#1]
I cannot retrieve the download link for the BDD-A dataset from the website provided. Could you please provide the complete BDD-A dataset? My email is s15300732652@gmail.com. Thanks.

**Comment by ykotseruba** [comment]
Thanks for pointing this out. The correct link to the dataset is bdd-data.berkeley.edu/download.html. As I am not the author/maintainer of the BDD-A  dataset, I cannot distribute the videos.
